"""created_by field added in cadastral repostirory table

Revision ID: a4c8d031cb33
Revises: baed7d39c593
Create Date: 2024-09-07 16:41:38.755236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c8d031cb33'
down_revision: Union[str, None] = 'baed7d39c593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cadastral_repository', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'cadastral_repository', ['cadastral_unique_id'])
    op.create_foreign_key(None, 'cadastral_repository', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cadastral_repository', type_='foreignkey')
    op.drop_constraint(None, 'cadastral_repository', type_='unique')
    op.drop_column('cadastral_repository', 'created_by')
    # ### end Alembic commands ###
